<?php

namespace Database\Seeders;

use App\Models\Archivo;
use App\Models\Inventario;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class InventarioSeeder extends Seeder
{
    /**
     * Presentaciones: 1=Caja, 2=Frasco, 3=Blister, 4=Ampolla, 5=Sachet,
     *                 6=Tubo, 7=Vial, 8=Sobre, 9=Bolsa, 10=Píldora
     * Categorías:     1=Medicamentos, 2=Suplementos, 3=Cuidado Personal,
     *                 4=Equipos Médicos, 5=Higiene
     * Subcategorías:  1=Dolor de cabeza, 2=Fiebre, 3=Resfriado, 4=Dolor muscular,
     *                 5=Alergias, 6=Problemas digestivos, 7=Dolor de garganta,
     *                 8=Tos, 9=Dolor de estómago, 10=Dolor de espalda
     * Áreas:          1=Tienda, 2=Almacén
     */
    public function run(): void
    {
        $medicamentos = [
            [
                'nombre' => 'Paracetamol 500mg',
                'codigo' => 'INV-001',
                'cantidad' => 350,
                'flag_blister' => true,
                'precio_blister' => '3.50',
                'cantidad_blister' => 10,
                'flag_unidad' => true,
                'precio_unidad' => '0.35',
                'stock_minimo' => '50',
                'precio_oficial' => '3.50',
                'fecha_vencimiento' => '2027-06-30',
                'registro_sanitario' => 'E.F.A. N° 21478',
                'lote' => 'LTE-2024001',
                'ubicacion' => 'A-01',
                'precio' => 3.50,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 3,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [1, 2],
                'imagen' => 'https://picsum.photos/seed/paracetamol/400/400',
            ],
            [
                'nombre' => 'Ibuprofeno 400mg',
                'codigo' => 'INV-002',
                'cantidad' => 280,
                'flag_blister' => true,
                'precio_blister' => '5.00',
                'cantidad_blister' => 10,
                'flag_unidad' => true,
                'precio_unidad' => '0.50',
                'stock_minimo' => '40',
                'precio_oficial' => '5.00',
                'fecha_vencimiento' => '2027-09-15',
                'registro_sanitario' => 'E.F.A. N° 19854',
                'lote' => 'LTE-2024002',
                'ubicacion' => 'A-02',
                'precio' => 5.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 3,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [1, 4, 10],
                'imagen' => 'https://picsum.photos/seed/ibuprofeno/400/400',
            ],
            [
                'nombre' => 'Amoxicilina 500mg',
                'codigo' => 'INV-003',
                'cantidad' => 120,
                'flag_blister' => true,
                'precio_blister' => '12.00',
                'cantidad_blister' => 12,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '20',
                'precio_oficial' => '12.00',
                'fecha_vencimiento' => '2026-12-31',
                'registro_sanitario' => 'E.F.A. N° 32541',
                'lote' => 'LTE-2024003',
                'ubicacion' => 'B-01',
                'precio' => 12.00,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 1,
                'laboratorio_id' => 3,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [3, 7],
                'imagen' => 'https://picsum.photos/seed/amoxicilina/400/400',
            ],
            [
                'nombre' => 'Metformina 850mg',
                'codigo' => 'INV-004',
                'cantidad' => 200,
                'flag_blister' => true,
                'precio_blister' => '8.50',
                'cantidad_blister' => 10,
                'flag_unidad' => true,
                'precio_unidad' => '0.85',
                'stock_minimo' => '30',
                'precio_oficial' => '8.50',
                'fecha_vencimiento' => '2028-03-20',
                'registro_sanitario' => 'E.F.A. N° 44127',
                'lote' => 'LTE-2024004',
                'ubicacion' => 'A-03',
                'precio' => 8.50,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 3,
                'laboratorio_id' => 4,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/metformina/400/400',
            ],
            [
                'nombre' => 'Atorvastatina 20mg',
                'codigo' => 'INV-005',
                'cantidad' => 150,
                'flag_blister' => true,
                'precio_blister' => '15.00',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '20',
                'precio_oficial' => '15.00',
                'fecha_vencimiento' => '2027-11-30',
                'registro_sanitario' => 'E.F.A. N° 52369',
                'lote' => 'LTE-2024005',
                'ubicacion' => 'A-04',
                'precio' => 15.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 3,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/atorvastatina/400/400',
            ],
            [
                'nombre' => 'Omeprazol 20mg',
                'codigo' => 'INV-006',
                'cantidad' => 220,
                'flag_blister' => true,
                'precio_blister' => '7.00',
                'cantidad_blister' => 14,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '30',
                'precio_oficial' => '7.00',
                'fecha_vencimiento' => '2027-04-15',
                'registro_sanitario' => 'E.F.A. N° 38741',
                'lote' => 'LTE-2024006',
                'ubicacion' => 'B-02',
                'precio' => 7.00,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 1,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [6, 9],
                'imagen' => 'https://picsum.photos/seed/omeprazol/400/400',
            ],
            [
                'nombre' => 'Losartán 50mg',
                'codigo' => 'INV-007',
                'cantidad' => 180,
                'flag_blister' => true,
                'precio_blister' => '10.00',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '25',
                'precio_oficial' => '10.00',
                'fecha_vencimiento' => '2028-01-31',
                'registro_sanitario' => 'E.F.A. N° 61234',
                'lote' => 'LTE-2024007',
                'ubicacion' => 'A-05',
                'precio' => 10.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 3,
                'laboratorio_id' => 3,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/losartan/400/400',
            ],
            [
                'nombre' => 'Amlodipino 5mg',
                'codigo' => 'INV-008',
                'cantidad' => 160,
                'flag_blister' => true,
                'precio_blister' => '9.00',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '20',
                'precio_oficial' => '9.00',
                'fecha_vencimiento' => '2027-08-20',
                'registro_sanitario' => 'E.F.A. N° 71852',
                'lote' => 'LTE-2024008',
                'ubicacion' => 'A-06',
                'precio' => 9.00,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 3,
                'laboratorio_id' => 4,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/amlodipino/400/400',
            ],
            [
                'nombre' => 'Loratadina 10mg',
                'codigo' => 'INV-009',
                'cantidad' => 240,
                'flag_blister' => true,
                'precio_blister' => '4.50',
                'cantidad_blister' => 10,
                'flag_unidad' => true,
                'precio_unidad' => '0.45',
                'stock_minimo' => '30',
                'precio_oficial' => '4.50',
                'fecha_vencimiento' => '2027-05-31',
                'registro_sanitario' => 'E.F.A. N° 82547',
                'lote' => 'LTE-2024009',
                'ubicacion' => 'A-07',
                'precio' => 4.50,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 3,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [5],
                'imagen' => 'https://picsum.photos/seed/loratadina/400/400',
            ],
            [
                'nombre' => 'Azitromicina 500mg',
                'codigo' => 'INV-010',
                'cantidad' => 90,
                'flag_blister' => true,
                'precio_blister' => '18.00',
                'cantidad_blister' => 3,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '15',
                'precio_oficial' => '18.00',
                'fecha_vencimiento' => '2026-10-15',
                'registro_sanitario' => 'E.F.A. N° 93614',
                'lote' => 'LTE-2024010',
                'ubicacion' => 'B-03',
                'precio' => 18.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 3,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [3, 7],
                'imagen' => 'https://picsum.photos/seed/azitromicina/400/400',
            ],
            [
                'nombre' => 'Ciprofloxacino 500mg',
                'codigo' => 'INV-011',
                'cantidad' => 100,
                'flag_blister' => true,
                'precio_blister' => '14.00',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '20',
                'precio_oficial' => '14.00',
                'fecha_vencimiento' => '2027-02-28',
                'registro_sanitario' => 'E.F.A. N° 10452',
                'lote' => 'LTE-2024011',
                'ubicacion' => 'B-04',
                'precio' => 14.00,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 3,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/ciprofloxacino/400/400',
            ],
            [
                'nombre' => 'Diclofenaco 75mg/3ml Inyectable',
                'codigo' => 'INV-012',
                'cantidad' => 80,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '2.50',
                'stock_minimo' => '15',
                'precio_oficial' => '2.50',
                'fecha_vencimiento' => '2027-07-31',
                'registro_sanitario' => 'E.F.A. N° 11748',
                'lote' => 'LTE-2024012',
                'ubicacion' => 'C-01',
                'precio' => 2.50,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 4,
                'laboratorio_id' => 3,
                'area_id' => 2,
                'categoria_ids' => [1],
                'subcategoria_ids' => [1, 4, 10],
                'imagen' => 'https://picsum.photos/seed/diclofenaco/400/400',
            ],
            [
                'nombre' => 'Captopril 25mg',
                'codigo' => 'INV-013',
                'cantidad' => 130,
                'flag_blister' => true,
                'precio_blister' => '6.00',
                'cantidad_blister' => 20,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '20',
                'precio_oficial' => '6.00',
                'fecha_vencimiento' => '2027-03-31',
                'registro_sanitario' => 'E.F.A. N° 12963',
                'lote' => 'LTE-2024013',
                'ubicacion' => 'A-08',
                'precio' => 6.00,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 3,
                'laboratorio_id' => 4,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/captopril/400/400',
            ],
            [
                'nombre' => 'Enalapril 10mg',
                'codigo' => 'INV-014',
                'cantidad' => 170,
                'flag_blister' => true,
                'precio_blister' => '7.50',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '25',
                'precio_oficial' => '7.50',
                'fecha_vencimiento' => '2028-05-31',
                'registro_sanitario' => 'E.F.A. N° 13574',
                'lote' => 'LTE-2024014',
                'ubicacion' => 'A-09',
                'precio' => 7.50,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 3,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/enalapril/400/400',
            ],
            [
                'nombre' => 'Salbutamol Inhalador 100mcg',
                'codigo' => 'INV-015',
                'cantidad' => 45,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '28.00',
                'stock_minimo' => '10',
                'precio_oficial' => '28.00',
                'fecha_vencimiento' => '2026-11-30',
                'registro_sanitario' => 'E.F.A. N° 14785',
                'lote' => 'LTE-2024015',
                'ubicacion' => 'D-01',
                'precio' => 28.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 1,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [8],
                'imagen' => 'https://picsum.photos/seed/salbutamol/400/400',
            ],
            [
                'nombre' => 'Metronidazol 500mg',
                'codigo' => 'INV-016',
                'cantidad' => 110,
                'flag_blister' => true,
                'precio_blister' => '8.00',
                'cantidad_blister' => 14,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '20',
                'precio_oficial' => '8.00',
                'fecha_vencimiento' => '2027-10-15',
                'registro_sanitario' => 'E.F.A. N° 15896',
                'lote' => 'LTE-2024016',
                'ubicacion' => 'B-05',
                'precio' => 8.00,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 3,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [6],
                'imagen' => 'https://picsum.photos/seed/metronidazol/400/400',
            ],
            [
                'nombre' => 'Dexametasona 4mg/2ml Inyectable',
                'codigo' => 'INV-017',
                'cantidad' => 60,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '3.00',
                'stock_minimo' => '10',
                'precio_oficial' => '3.00',
                'fecha_vencimiento' => '2027-01-31',
                'registro_sanitario' => 'E.F.A. N° 16907',
                'lote' => 'LTE-2024017',
                'ubicacion' => 'C-02',
                'precio' => 3.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 4,
                'laboratorio_id' => 3,
                'area_id' => 2,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/dexametasona/400/400',
            ],
            [
                'nombre' => 'Prednisona 20mg',
                'codigo' => 'INV-018',
                'cantidad' => 95,
                'flag_blister' => true,
                'precio_blister' => '9.50',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '15',
                'precio_oficial' => '9.50',
                'fecha_vencimiento' => '2028-04-30',
                'registro_sanitario' => 'E.F.A. N° 17018',
                'lote' => 'LTE-2024018',
                'ubicacion' => 'A-10',
                'precio' => 9.50,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 3,
                'laboratorio_id' => 4,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/prednisona/400/400',
            ],
            [
                'nombre' => 'Vitamina C 1000mg Efervescente',
                'codigo' => 'INV-019',
                'cantidad' => 300,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '0.80',
                'stock_minimo' => '50',
                'precio_oficial' => '16.00',
                'fecha_vencimiento' => '2027-12-31',
                'registro_sanitario' => 'E.F.A. N° 18129',
                'lote' => 'LTE-2024019',
                'ubicacion' => 'E-01',
                'precio' => 16.00,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 2,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [2],
                'subcategoria_ids' => [3],
                'imagen' => 'https://picsum.photos/seed/vitamina-c/400/400',
            ],
            [
                'nombre' => 'Vitamina D3 2000 UI',
                'codigo' => 'INV-020',
                'cantidad' => 180,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '0.60',
                'stock_minimo' => '30',
                'precio_oficial' => '18.00',
                'fecha_vencimiento' => '2028-02-28',
                'registro_sanitario' => 'E.F.A. N° 19230',
                'lote' => 'LTE-2024020',
                'ubicacion' => 'E-02',
                'precio' => 18.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 2,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [2],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/vitamina-d/400/400',
            ],
            [
                'nombre' => 'Complejo B Forte',
                'codigo' => 'INV-021',
                'cantidad' => 210,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '0.50',
                'stock_minimo' => '30',
                'precio_oficial' => '15.00',
                'fecha_vencimiento' => '2027-07-15',
                'registro_sanitario' => 'E.F.A. N° 20341',
                'lote' => 'LTE-2024021',
                'ubicacion' => 'E-03',
                'precio' => 15.00,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 2,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [2],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/complejo-b/400/400',
            ],
            [
                'nombre' => 'Calcio + Vitamina D3 600mg',
                'codigo' => 'INV-022',
                'cantidad' => 160,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '0.70',
                'stock_minimo' => '25',
                'precio_oficial' => '21.00',
                'fecha_vencimiento' => '2028-06-30',
                'registro_sanitario' => 'E.F.A. N° 21452',
                'lote' => 'LTE-2024022',
                'ubicacion' => 'E-04',
                'precio' => 21.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 2,
                'laboratorio_id' => 3,
                'area_id' => 1,
                'categoria_ids' => [2],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/calcio-vit-d/400/400',
            ],
            [
                'nombre' => 'Sulfato Ferroso 300mg',
                'codigo' => 'INV-023',
                'cantidad' => 140,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '0.30',
                'stock_minimo' => '20',
                'precio_oficial' => '9.00',
                'fecha_vencimiento' => '2027-09-30',
                'registro_sanitario' => 'E.F.A. N° 22563',
                'lote' => 'LTE-2024023',
                'ubicacion' => 'E-05',
                'precio' => 9.00,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 2,
                'laboratorio_id' => 4,
                'area_id' => 1,
                'categoria_ids' => [1, 2],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/sulfato-ferroso/400/400',
            ],
            [
                'nombre' => 'Ácido Fólico 5mg',
                'codigo' => 'INV-024',
                'cantidad' => 190,
                'flag_blister' => true,
                'precio_blister' => '4.00',
                'cantidad_blister' => 20,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '30',
                'precio_oficial' => '4.00',
                'fecha_vencimiento' => '2028-01-15',
                'registro_sanitario' => 'E.F.A. N° 23674',
                'lote' => 'LTE-2024024',
                'ubicacion' => 'E-06',
                'precio' => 4.00,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 3,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [1, 2],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/acido-folico/400/400',
            ],
            [
                'nombre' => 'Melatonina 3mg',
                'codigo' => 'INV-025',
                'cantidad' => 120,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '0.90',
                'stock_minimo' => '20',
                'precio_oficial' => '27.00',
                'fecha_vencimiento' => '2027-08-31',
                'registro_sanitario' => 'E.F.A. N° 24785',
                'lote' => 'LTE-2024025',
                'ubicacion' => 'E-07',
                'precio' => 27.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 2,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [2],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/melatonina/400/400',
            ],
            [
                'nombre' => 'Ranitidina 150mg',
                'codigo' => 'INV-026',
                'cantidad' => 175,
                'flag_blister' => true,
                'precio_blister' => '5.50',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '25',
                'precio_oficial' => '5.50',
                'fecha_vencimiento' => '2027-05-20',
                'registro_sanitario' => 'E.F.A. N° 25896',
                'lote' => 'LTE-2024026',
                'ubicacion' => 'B-06',
                'precio' => 5.50,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 3,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [6, 9],
                'imagen' => 'https://picsum.photos/seed/ranitidina/400/400',
            ],
            [
                'nombre' => 'Lansoprazol 30mg',
                'codigo' => 'INV-027',
                'cantidad' => 140,
                'flag_blister' => true,
                'precio_blister' => '11.00',
                'cantidad_blister' => 14,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '20',
                'precio_oficial' => '11.00',
                'fecha_vencimiento' => '2027-11-15',
                'registro_sanitario' => 'E.F.A. N° 26907',
                'lote' => 'LTE-2024027',
                'ubicacion' => 'B-07',
                'precio' => 11.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 1,
                'laboratorio_id' => 3,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [6, 9],
                'imagen' => 'https://picsum.photos/seed/lansoprazol/400/400',
            ],
            [
                'nombre' => 'Pantoprazol 40mg',
                'codigo' => 'INV-028',
                'cantidad' => 130,
                'flag_blister' => true,
                'precio_blister' => '13.00',
                'cantidad_blister' => 14,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '20',
                'precio_oficial' => '13.00',
                'fecha_vencimiento' => '2028-03-31',
                'registro_sanitario' => 'E.F.A. N° 27018',
                'lote' => 'LTE-2024028',
                'ubicacion' => 'B-08',
                'precio' => 13.00,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 3,
                'laboratorio_id' => 4,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [6, 9],
                'imagen' => 'https://picsum.photos/seed/pantoprazol/400/400',
            ],
            [
                'nombre' => 'Bisoprolol 5mg',
                'codigo' => 'INV-029',
                'cantidad' => 115,
                'flag_blister' => true,
                'precio_blister' => '12.00',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '15',
                'precio_oficial' => '12.00',
                'fecha_vencimiento' => '2027-06-15',
                'registro_sanitario' => 'E.F.A. N° 28129',
                'lote' => 'LTE-2024029',
                'ubicacion' => 'A-11',
                'precio' => 12.00,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 3,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/bisoprolol/400/400',
            ],
            [
                'nombre' => 'Furosemida 40mg',
                'codigo' => 'INV-030',
                'cantidad' => 105,
                'flag_blister' => true,
                'precio_blister' => '6.50',
                'cantidad_blister' => 20,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '15',
                'precio_oficial' => '6.50',
                'fecha_vencimiento' => '2027-04-30',
                'registro_sanitario' => 'E.F.A. N° 29240',
                'lote' => 'LTE-2024030',
                'ubicacion' => 'A-12',
                'precio' => 6.50,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 3,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/furosemida/400/400',
            ],
            [
                'nombre' => 'Espironolactona 25mg',
                'codigo' => 'INV-031',
                'cantidad' => 85,
                'flag_blister' => true,
                'precio_blister' => '9.00',
                'cantidad_blister' => 20,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '10',
                'precio_oficial' => '9.00',
                'fecha_vencimiento' => '2027-10-31',
                'registro_sanitario' => 'E.F.A. N° 30351',
                'lote' => 'LTE-2024031',
                'ubicacion' => 'A-13',
                'precio' => 9.00,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 3,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/espironolactona/400/400',
            ],
            [
                'nombre' => 'Sertralina 50mg',
                'codigo' => 'INV-032',
                'cantidad' => 75,
                'flag_blister' => true,
                'precio_blister' => '16.00',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '10',
                'precio_oficial' => '16.00',
                'fecha_vencimiento' => '2028-02-15',
                'registro_sanitario' => 'E.F.A. N° 31462',
                'lote' => 'LTE-2024032',
                'ubicacion' => 'F-01',
                'precio' => 16.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 3,
                'laboratorio_id' => 3,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/sertralina/400/400',
            ],
            [
                'nombre' => 'Fluoxetina 20mg',
                'codigo' => 'INV-033',
                'cantidad' => 80,
                'flag_blister' => true,
                'precio_blister' => '14.00',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '10',
                'precio_oficial' => '14.00',
                'fecha_vencimiento' => '2027-12-31',
                'registro_sanitario' => 'E.F.A. N° 32573',
                'lote' => 'LTE-2024033',
                'ubicacion' => 'F-02',
                'precio' => 14.00,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 3,
                'laboratorio_id' => 4,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/fluoxetina/400/400',
            ],
            [
                'nombre' => 'Amitriptilina 25mg',
                'codigo' => 'INV-034',
                'cantidad' => 65,
                'flag_blister' => true,
                'precio_blister' => '8.00',
                'cantidad_blister' => 20,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '10',
                'precio_oficial' => '8.00',
                'fecha_vencimiento' => '2027-08-15',
                'registro_sanitario' => 'E.F.A. N° 33684',
                'lote' => 'LTE-2024034',
                'ubicacion' => 'F-03',
                'precio' => 8.00,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 3,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/amitriptilina/400/400',
            ],
            [
                'nombre' => 'Clonazepam 0.5mg',
                'codigo' => 'INV-035',
                'cantidad' => 55,
                'flag_blister' => true,
                'precio_blister' => '11.00',
                'cantidad_blister' => 30,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '10',
                'precio_oficial' => '11.00',
                'fecha_vencimiento' => '2027-03-15',
                'registro_sanitario' => 'E.F.A. N° 34795',
                'lote' => 'LTE-2024035',
                'ubicacion' => 'F-04',
                'precio' => 11.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 3,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/clonazepam/400/400',
            ],
            [
                'nombre' => 'Gabapentina 300mg',
                'codigo' => 'INV-036',
                'cantidad' => 70,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '1.20',
                'stock_minimo' => '10',
                'precio_oficial' => '36.00',
                'fecha_vencimiento' => '2028-07-31',
                'registro_sanitario' => 'E.F.A. N° 35806',
                'lote' => 'LTE-2024036',
                'ubicacion' => 'F-05',
                'precio' => 36.00,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 1,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [4, 10],
                'imagen' => 'https://picsum.photos/seed/gabapentina/400/400',
            ],
            [
                'nombre' => 'Tramadol 50mg',
                'codigo' => 'INV-037',
                'cantidad' => 50,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '1.50',
                'stock_minimo' => '10',
                'precio_oficial' => '30.00',
                'fecha_vencimiento' => '2027-05-15',
                'registro_sanitario' => 'E.F.A. N° 36917',
                'lote' => 'LTE-2024037',
                'ubicacion' => 'F-06',
                'precio' => 30.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 1,
                'laboratorio_id' => 3,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [1, 4, 10],
                'imagen' => 'https://picsum.photos/seed/tramadol/400/400',
            ],
            [
                'nombre' => 'Ketorolaco 30mg/1ml Inyectable',
                'codigo' => 'INV-038',
                'cantidad' => 40,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '3.50',
                'stock_minimo' => '8',
                'precio_oficial' => '3.50',
                'fecha_vencimiento' => '2027-09-20',
                'registro_sanitario' => 'E.F.A. N° 37028',
                'lote' => 'LTE-2024038',
                'ubicacion' => 'C-03',
                'precio' => 3.50,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 4,
                'laboratorio_id' => 4,
                'area_id' => 2,
                'categoria_ids' => [1],
                'subcategoria_ids' => [1, 4],
                'imagen' => 'https://picsum.photos/seed/ketorolaco/400/400',
            ],
            [
                'nombre' => 'Naproxeno 500mg',
                'codigo' => 'INV-039',
                'cantidad' => 195,
                'flag_blister' => true,
                'precio_blister' => '7.00',
                'cantidad_blister' => 10,
                'flag_unidad' => true,
                'precio_unidad' => '0.70',
                'stock_minimo' => '30',
                'precio_oficial' => '7.00',
                'fecha_vencimiento' => '2027-07-31',
                'registro_sanitario' => 'E.F.A. N° 38139',
                'lote' => 'LTE-2024039',
                'ubicacion' => 'A-14',
                'precio' => 7.00,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 3,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [1, 4, 10],
                'imagen' => 'https://picsum.photos/seed/naproxeno/400/400',
            ],
            [
                'nombre' => 'Celecoxib 200mg',
                'codigo' => 'INV-040',
                'cantidad' => 85,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '1.80',
                'stock_minimo' => '15',
                'precio_oficial' => '36.00',
                'fecha_vencimiento' => '2028-04-15',
                'registro_sanitario' => 'E.F.A. N° 39250',
                'lote' => 'LTE-2024040',
                'ubicacion' => 'A-15',
                'precio' => 36.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 1,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [4, 10],
                'imagen' => 'https://picsum.photos/seed/celecoxib/400/400',
            ],
            [
                'nombre' => 'Claritromicina 500mg',
                'codigo' => 'INV-041',
                'cantidad' => 75,
                'flag_blister' => true,
                'precio_blister' => '20.00',
                'cantidad_blister' => 14,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '10',
                'precio_oficial' => '20.00',
                'fecha_vencimiento' => '2026-11-15',
                'registro_sanitario' => 'E.F.A. N° 40361',
                'lote' => 'LTE-2024041',
                'ubicacion' => 'B-09',
                'precio' => 20.00,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 3,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [3, 7],
                'imagen' => 'https://picsum.photos/seed/claritromicina/400/400',
            ],
            [
                'nombre' => 'Doxiciclina 100mg',
                'codigo' => 'INV-042',
                'cantidad' => 60,
                'flag_blister' => true,
                'precio_blister' => '10.00',
                'cantidad_blister' => 10,
                'flag_unidad' => false,
                'precio_unidad' => null,
                'stock_minimo' => '10',
                'precio_oficial' => '10.00',
                'fecha_vencimiento' => '2027-01-20',
                'registro_sanitario' => 'E.F.A. N° 41472',
                'lote' => 'LTE-2024042',
                'ubicacion' => 'B-10',
                'precio' => 10.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 3,
                'laboratorio_id' => 3,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/doxiciclina/400/400',
            ],
            [
                'nombre' => 'Fluconazol 150mg',
                'codigo' => 'INV-043',
                'cantidad' => 50,
                'flag_blister' => true,
                'precio_blister' => '8.50',
                'cantidad_blister' => 1,
                'flag_unidad' => true,
                'precio_unidad' => '8.50',
                'stock_minimo' => '10',
                'precio_oficial' => '8.50',
                'fecha_vencimiento' => '2027-06-20',
                'registro_sanitario' => 'E.F.A. N° 42583',
                'lote' => 'LTE-2024043',
                'ubicacion' => 'B-11',
                'precio' => 8.50,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 3,
                'laboratorio_id' => 4,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/fluconazol/400/400',
            ],
            [
                'nombre' => 'Clotrimazol Crema 1% 20g',
                'codigo' => 'INV-044',
                'cantidad' => 70,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '9.00',
                'stock_minimo' => '10',
                'precio_oficial' => '9.00',
                'fecha_vencimiento' => '2028-08-31',
                'registro_sanitario' => 'E.F.A. N° 43694',
                'lote' => 'LTE-2024044',
                'ubicacion' => 'G-01',
                'precio' => 9.00,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 6,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [3],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/clotrimazol/400/400',
            ],
            [
                'nombre' => 'Hidrocortisona Crema 1% 30g',
                'codigo' => 'INV-045',
                'cantidad' => 55,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '11.00',
                'stock_minimo' => '10',
                'precio_oficial' => '11.00',
                'fecha_vencimiento' => '2028-05-15',
                'registro_sanitario' => 'E.F.A. N° 44705',
                'lote' => 'LTE-2024045',
                'ubicacion' => 'G-02',
                'precio' => 11.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 6,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [3],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/hidrocortisona/400/400',
            ],
            [
                'nombre' => 'Betametasona Crema 0.05% 20g',
                'codigo' => 'INV-046',
                'cantidad' => 45,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '13.00',
                'stock_minimo' => '8',
                'precio_oficial' => '13.00',
                'fecha_vencimiento' => '2027-12-15',
                'registro_sanitario' => 'E.F.A. N° 45816',
                'lote' => 'LTE-2024046',
                'ubicacion' => 'G-03',
                'precio' => 13.00,
                'flag_disponible' => true,
                'proveedor_id' => 1,
                'presentacion_id' => 6,
                'laboratorio_id' => 2,
                'area_id' => 1,
                'categoria_ids' => [3],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/betametasona/400/400',
            ],
            [
                'nombre' => 'Alcohol Isopropílico 70% 250ml',
                'codigo' => 'INV-047',
                'cantidad' => 400,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '5.00',
                'stock_minimo' => '50',
                'precio_oficial' => '5.00',
                'fecha_vencimiento' => '2028-12-31',
                'registro_sanitario' => 'E.F.A. N° 46927',
                'lote' => 'LTE-2024047',
                'ubicacion' => 'H-01',
                'precio' => 5.00,
                'flag_disponible' => true,
                'proveedor_id' => 2,
                'presentacion_id' => 2,
                'laboratorio_id' => 3,
                'area_id' => 2,
                'categoria_ids' => [3, 5],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/alcohol-isopropilico/400/400',
            ],
            [
                'nombre' => 'Agua Oxigenada 10V 120ml',
                'codigo' => 'INV-048',
                'cantidad' => 350,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '3.50',
                'stock_minimo' => '50',
                'precio_oficial' => '3.50',
                'fecha_vencimiento' => '2028-09-30',
                'registro_sanitario' => 'E.F.A. N° 47038',
                'lote' => 'LTE-2024048',
                'ubicacion' => 'H-02',
                'precio' => 3.50,
                'flag_disponible' => true,
                'proveedor_id' => 3,
                'presentacion_id' => 2,
                'laboratorio_id' => 4,
                'area_id' => 2,
                'categoria_ids' => [3, 5],
                'subcategoria_ids' => [],
                'imagen' => 'https://picsum.photos/seed/agua-oxigenada/400/400',
            ],
            [
                'nombre' => 'Suero Oral Rehidratante',
                'codigo' => 'INV-049',
                'cantidad' => 260,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '1.00',
                'stock_minimo' => '40',
                'precio_oficial' => '1.00',
                'fecha_vencimiento' => '2028-06-15',
                'registro_sanitario' => 'E.F.A. N° 48149',
                'lote' => 'LTE-2024049',
                'ubicacion' => 'I-01',
                'precio' => 1.00,
                'flag_disponible' => true,
                'proveedor_id' => 4,
                'presentacion_id' => 8,
                'laboratorio_id' => 5,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [6, 9],
                'imagen' => 'https://picsum.photos/seed/suero-oral/400/400',
            ],
            [
                'nombre' => 'Ibuprofeno Jarabe 200mg/5ml',
                'codigo' => 'INV-050',
                'cantidad' => 145,
                'flag_blister' => false,
                'precio_blister' => null,
                'cantidad_blister' => null,
                'flag_unidad' => true,
                'precio_unidad' => '12.00',
                'stock_minimo' => '20',
                'precio_oficial' => '12.00',
                'fecha_vencimiento' => '2027-03-31',
                'registro_sanitario' => 'E.F.A. N° 49250',
                'lote' => 'LTE-2024050',
                'ubicacion' => 'J-01',
                'precio' => 12.00,
                'flag_disponible' => true,
                'proveedor_id' => 5,
                'presentacion_id' => 2,
                'laboratorio_id' => 1,
                'area_id' => 1,
                'categoria_ids' => [1],
                'subcategoria_ids' => [1, 2, 4],
                'imagen' => 'https://picsum.photos/seed/ibuprofeno-jarabe/400/400',
            ],
        ];

        foreach ($medicamentos as $data) {
            $inventario = Inventario::create([
                'nombre'             => $data['nombre'],
                'codigo'             => $data['codigo'],
                'cantidad'           => $data['cantidad'],
                'flag_blister'       => $data['flag_blister'],
                'precio_blister'     => $data['precio_blister'],
                'cantidad_blister'   => $data['cantidad_blister'],
                'flag_unidad'        => $data['flag_unidad'],
                'precio_unidad'      => $data['precio_unidad'],
                'stock_minimo'       => $data['stock_minimo'],
                'precio_oficial'     => $data['precio_oficial'],
                'fecha_vencimiento'  => $data['fecha_vencimiento'],
                'registro_sanitario' => $data['registro_sanitario'],
                'lote'               => $data['lote'],
                'ubicacion'          => $data['ubicacion'],
                'precio'             => $data['precio'],
                'flag_disponible'    => $data['flag_disponible'],
                'proveedor_id'       => $data['proveedor_id'],
                'presentacion_id'    => $data['presentacion_id'],
                'laboratorio_id'     => $data['laboratorio_id'],
                'area_id'            => $data['area_id'],
            ]);

            if (!empty($data['categoria_ids'])) {
                $inventario->categorias()->attach($data['categoria_ids']);
            }

            if (!empty($data['subcategoria_ids'])) {
                $inventario->subcategorias()->attach($data['subcategoria_ids']);
            }

            Archivo::create([
                'archivable_id'   => $inventario->id,
                'archivable_type' => Inventario::class,
                'nombre'          => Str::slug($data['nombre']) . '.jpg',
                'url'             => $data['imagen'],
                'tipo_1'          => 'imagen',
                'tipo_2'          => 'jpg',
            ]);
        }
    }
}
